//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
using System.Xml.Serialization;
namespace UploadDaemon.SymbolAnalysis
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(ElementName = "results", Namespace = "", IsNullable = false)]
    public partial class VsCoverageResults
    {

        private resultsModule[] modulesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("module", IsNullable = false)]
        public resultsModule[] modules
        {
            get
            {
                return this.modulesField;
            }
            set
            {
                this.modulesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class resultsModule
    {

        private resultsModuleFunction[] functionsField;

        private resultsModuleSource_file[] source_filesField;

        private string nameField;

        private string pathField;

        private string idField;

        private decimal block_coverageField;

        private decimal line_coverageField;

        private int blocks_coveredField;

        private int blocks_not_coveredField;

        private int lines_coveredField;

        private int lines_partially_coveredField;

        private int lines_not_coveredField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("function", IsNullable = false)]
        public resultsModuleFunction[] functions
        {
            get
            {
                return this.functionsField;
            }
            set
            {
                this.functionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("source_file", IsNullable = false)]
        public resultsModuleSource_file[] source_files
        {
            get
            {
                return this.source_filesField;
            }
            set
            {
                this.source_filesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal block_coverage
        {
            get
            {
                return this.block_coverageField;
            }
            set
            {
                this.block_coverageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal line_coverage
        {
            get
            {
                return this.line_coverageField;
            }
            set
            {
                this.line_coverageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int blocks_covered
        {
            get
            {
                return this.blocks_coveredField;
            }
            set
            {
                this.blocks_coveredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int blocks_not_covered
        {
            get
            {
                return this.blocks_not_coveredField;
            }
            set
            {
                this.blocks_not_coveredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int lines_covered
        {
            get
            {
                return this.lines_coveredField;
            }
            set
            {
                this.lines_coveredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int lines_partially_covered
        {
            get
            {
                return this.lines_partially_coveredField;
            }
            set
            {
                this.lines_partially_coveredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int lines_not_covered
        {
            get
            {
                return this.lines_not_coveredField;
            }
            set
            {
                this.lines_not_coveredField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class resultsModuleFunction
    {

        private resultsModuleFunctionRange[] rangesField;

        private uint idField;

        private string tokenField;

        private string nameField;

        private string namespaceField;

        private string type_nameField;

        private decimal block_coverageField;

        private decimal line_coverageField;

        private int blocks_coveredField;

        private int blocks_not_coveredField;

        private int lines_coveredField;

        private int lines_partially_coveredField;

        private int lines_not_coveredField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("range", IsNullable = false)]
        public resultsModuleFunctionRange[] ranges
        {
            get
            {
                return this.rangesField;
            }
            set
            {
                this.rangesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @namespace
        {
            get
            {
                return this.namespaceField;
            }
            set
            {
                this.namespaceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type_name
        {
            get
            {
                return this.type_nameField;
            }
            set
            {
                this.type_nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal block_coverage
        {
            get
            {
                return this.block_coverageField;
            }
            set
            {
                this.block_coverageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal line_coverage
        {
            get
            {
                return this.line_coverageField;
            }
            set
            {
                this.line_coverageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int blocks_covered
        {
            get
            {
                return this.blocks_coveredField;
            }
            set
            {
                this.blocks_coveredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int blocks_not_covered
        {
            get
            {
                return this.blocks_not_coveredField;
            }
            set
            {
                this.blocks_not_coveredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int lines_covered
        {
            get
            {
                return this.lines_coveredField;
            }
            set
            {
                this.lines_coveredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int lines_partially_covered
        {
            get
            {
                return this.lines_partially_coveredField;
            }
            set
            {
                this.lines_partially_coveredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int lines_not_covered
        {
            get
            {
                return this.lines_not_coveredField;
            }
            set
            {
                this.lines_not_coveredField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class resultsModuleFunctionRange
    {

        private int source_idField;

        private string coveredField;

        private ushort start_lineField;

        private byte start_columnField;

        private ushort end_lineField;

        private byte end_columnField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int source_id
        {
            get
            {
                return this.source_idField;
            }
            set
            {
                this.source_idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string covered
        {
            get
            {
                return this.coveredField;
            }
            set
            {
                this.coveredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort start_line
        {
            get
            {
                return this.start_lineField;
            }
            set
            {
                this.start_lineField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte start_column
        {
            get
            {
                return this.start_columnField;
            }
            set
            {
                this.start_columnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort end_line
        {
            get
            {
                return this.end_lineField;
            }
            set
            {
                this.end_lineField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte end_column
        {
            get
            {
                return this.end_columnField;
            }
            set
            {
                this.end_columnField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class resultsModuleSource_file
    {

        private int idField;

        private string pathField;

        private string checksum_typeField;

        private string checksumField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string checksum_type
        {
            get
            {
                return this.checksum_typeField;
            }
            set
            {
                this.checksum_typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string checksum
        {
            get
            {
                return this.checksumField;
            }
            set
            {
                this.checksumField = value;
            }
        }
    }
}
